# Generated by Django 5.1.3 on 2024-11-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fullname", models.CharField(default="@fullname", max_length=254)),
                (
                    "username",
                    models.CharField(
                        default="@username",
                        max_length=254,
                        unique=True,
                        verbose_name="@",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="xxx@email.com", max_length=254, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="UserConnections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_time", models.DateTimeField(auto_now_add=True)),
                (
                    "followed",
                    models.ForeignKey(
                        blank=True,
                        default="@followed",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_set",
                        to="users.user",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        blank=True,
                        default="@follower",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_set",
                        to="users.user",
                    ),
                ),
                (
                    "user_main",
                    models.ForeignKey(
                        blank=True,
                        default="@user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_main_set",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
