# Generated by Django 5.1.3 on 2024-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=254)),
                ("username", models.CharField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=254)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
