services:
  db:
    image: postgres:17.1-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=twitter_dev
      - POSTGRES_PASSWORD=twitter_dev
      - POSTGRES_DB=twitter_dev_db

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db 

volumes:
  postgres_data:
  app_data: